### PR TITLE
Only do passive learning when it isn't school time

### LINKED ISSUE #11: Remove passive learning phase from school time
Following on from #10:

> On a school day we should have 5.5h of school learning which involves no passive learning; plus 5.5h of passive learning corresponding to out of school time On holidays we should have 11 hrs of passive learning.

The code should be modified so that the passive learning phase is not run during school time.

### PR DESCRIPTION
**Pull request by alisonrclarke**
Fixes #11

### CODE REVIEW

**Comment by PeterTymms** [comment]
I see your comment about the inevitability of more learning at home. I know about this and I was adjusting the poarameters to sort this out spcifically by reducting the multiplier of 1.2. I had also put in a term for home background.  This is the line that I was working on - you will see that I added a non-ability related amount of growth because then grwoth was too tied to ability:
set end_maths end_maths + 0.5 * (( (6 - deprivation) / 3) ^ .01) * (((random-normal ((5 + ability) / 2000) .08) ) + ((random-normal (5 / 2000) .08)

**Comment by alisonrclarke** [comment]
Thanks Peter. Would you be able to push your code to a branch so I can integrate it into the main repo? Let me know if you want a call to discuss.

**Comment by PeterTymms** [comment]
Can we discuss tomorrow? Say 10.30am? Sent from Mail for Windows 10 From: Alison ClarkeSent: 05 November 2020 17:14To: DurhamARC/classroom-abmCc: PeterTymms; CommentSubject: Re: [DurhamARC/classroom-abm] Only do passive learning when it isn't school time (#14) Thanks Peter. Would you be able to push your code to a branch so I can integrate it into the main repo? Let me know if you want a call to discuss.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PeterTymms** [comment]
I can’t do then I’m afraid

Professor Chris Brown
Professor in Education
Director of Research

Room 221a
School of Education
Durham University
Leazes Road
Durham
DH1 1TA

• chris.brown@durham.ac.uk<mailto:chris.brown@durham.ac.uk>
• +44 191 334 8368
@ chrisbrown1475

New books for 2020:

The Networked School Leader: How to improve teaching and student outcomes using learning networks<https://www.amazon.co.uk/gp/product/1838677224/ref=dbs_a_def_rwt_bibl_vppi_i3>
by Chris Brown

The Research-Informed Teaching Revolution: a handbook for the 21st century teacher<https://www.amazon.co.uk/gp/product/191290683X/ref=dbs_a_def_rwt_bibl_vppi_i4>
Edited by Chris Brown, Jane Flood and Graham Handscomb.


You may also be interested in: Networks for Learning: Effective Collaboration for Teacher, School and System Improvement<https://www.amazon.co.uk/Networks-Learning-Chris-Brown/dp/1138244767> Edited by Chris Brown and Cindy Poortman


From: "TYMMS, PETER B." <peter.tymms@gmail.com>
Date: Thursday, 5 November 2020 at 17:35
To: DurhamARC/classroom-abm <reply@reply.github.com>, "BROWN, CHRIS D." <chris.brown@durham.ac.uk>
Subject: RE: [DurhamARC/classroom-abm] Only do passive learning when it isn't school time (#14)


[EXTERNAL EMAIL] Do not open links or attachments unless you recognise the sender and know the content is safe. Otherwise, use the Report Message button or report to phishing@durham.ac.uk<mailto:phishing@durham.ac.uk>.
Can we discuss tomorrow? Say 10.30am?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PeterTymms** [comment]
Not to worry, I can keep you in the loop

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PeterTymms** [comment]
I hope I have deposited 3 files Sent from Mail for Windows 10 From: Alison ClarkeSent: 05 November 2020 17:14To: DurhamARC/classroom-abmCc: PeterTymms; CommentSubject: Re: [DurhamARC/classroom-abm] Only do passive learning when it isn't school time (#14) Thanks Peter. Would you be able to push your code to a branch so I can integrate it into the main repo? Let me know if you want a call to discuss.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
